// Generated by picasso
#pragma once
#define VSH_FVEC_projection 0x00
#define VSH_ULEN_projection 4
#define VSH_FVEC_model 0x04
#define VSH_ULEN_model 4
#define VSH_FVEC_view 0x08
#define VSH_ULEN_view 4
